name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy-to-EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: 65.1.3.201
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            ls
            whoami